apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: my-java-app-build-pipeline
spec:
  params:
  - name: MAVEN_IMAGE
    type: string
    default: maven:3.8-openjdk-11
  - name: GIT_REPO_URL
    type: string
    default: "https://github.com/residentorca/my-java-app.git"
  - name: GIT_REVISION
    type: string
    default: "main"
  workspaces:
  - name: source-workspace
  - name: shared-workspace
  tasks:
  - name: fetch-repo
    taskRef:
      name: git-clone
    params:
    - name: url
      value: $(params.GIT_REPO_URL)
    - name: revision
      value: $(params.GIT_REVISION)
    workspaces:
    - name: source-workspace
      workspace: source-workspace
  - name: build-java-app
    taskRef:
      name: maven-build
    params:
    - name: MAVEN_IMAGE
      value: $(params.MAVEN_IMAGE)
    workspaces:
    - name: source-workspace
      workspace: source-workspace
    - name: shared-workspace
      workspace: shared-workspace
    runAfter:
    - fetch-repo
  - name: build-and-push-image  # New task for building and pushing the image
    taskRef:
      name: build-and-push
    params:
      - name: IMAGE
        value: ghcr.io/residentorca/my-java-app  # Specify your image name here
      - name: TAG
        value: latest  # Or the specific tag you wish to use
    workspaces:
      - name: source-workspace
        workspace: source-workspace
    runAfter:
      - build-java-app  # Ensure this runs after the build-java-app task